### ISSUE TITLE
BPMが変化すると落ちる

### ISSUE THREAD

**Issue by Salt-01** [TJAPlayer3-Develop/TJAPlayer3-Develop#53] opened 2020-10-30 23:35 UTC
**注意: お使いのTJAPlayer3-Developが最新のバージョンであること確認してください！**

## 内容
BPMが変化すると応答しなくなって落ちます

## 発生手順
バグ/問題を発生する方法があります。
1.BPMが変わる曲をプレイします。
2.BPMが変わった瞬間に落ちます。

## 正常時の挙動
BPMが普通に変わる

## 動作環境
Windows10
CPU Intel CORE i7-8700 
メモリ　16GB
GPU NVIDIA GeForce GTX 1660

## その他の情報
![TJAPlayer3-Develop - v1 0 (WASAPI(0ms)) 2020_10_31 8_28_04](https://user-images.githubusercontent.com/71972640/97765050-08933500-1b54-11eb-8303-a6e64b3b9283.png)

**Comment by brian218** [comment] 2020-10-31 00:14
I can't reproduce the problem on my side using the latest release.
Could you please attach screenshot(s), TJAPlayer3.log and the song you were playing?

**Comment by Salt-01** [comment] 2020-10-31 00:32
https://www.youtube.com/watch?v=fURJ0sw_b5s
↑譜面です
![TJAPlayer3-Develop - v1 0 (WASAPI(0ms)) 2020_10_31 8_28_04](https://user-images.githubusercontent.com/71972640/97766880-eac9ce00-1b5b-11eb-8d7a-3dbb906ddee0.png)

[TJAPlayer3.log](https://github.com/TJAPlayer3-Develop/TJAPlayer3-Develop/files/5468251/TJAPlayer3.log)

**Comment by Salt-01** [comment] 2020-10-31 00:32
I'll try to re-download it once.

**Comment by Salt-01** [comment] 2020-10-31 00:37
We've solved it! I'm sorry to bother you.

**Comment by brian218** [comment] 2020-10-31 00:41
No problem. But could you share with us what the cause is and how you solved it?

**Comment by Salt-01** [comment] 2020-10-31 00:45
I'm not sure, but I think it's because I put the previous version of Config.ini and SkinConfig.ini directly into the latest version. The solution is to re-download it and that will solve the problem.

**Comment by brian218** [comment] 2020-10-31 00:54
Thanks for the clarification!
As confirmed, I'll go ahead by closing this issue.

**Closed as completed by brian218** 2020-10-31 00:54 UTC
Labels: 解決済み / Solved
